version: "3.8"

services:
  nextjs:
    build: .
    container_name: nextjs-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - nextjs
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge